name: Push Docker Image

on:
    push:
        branches:
        - master
    release:
        types: [published]

env:
    DOCKER_BASE_NAME: ghcr.io/${{ github.repository }}/doxygen

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Set env
          run: |
            if [ "${{ github.event_name }}" = 'release' ]; then
                export TAG_NAME="${{ github.event.release.tag_name }}"
            else
                export TAG_NAME="latest"
            fi
            echo "PKG_TAG=${DOCKER_BASE_NAME}:${TAG_NAME}" >> $GITHUB_ENV
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.CR_PAT }}

        - name: Build image
          run: docker build . -t "${PKG_TAG}"

        - name: Push to GitHub Packages
          run: docker push "${PKG_TAG}"